In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from matplotlib import style
sns.set(style='whitegrid',color_codes=True)

import warnings
warnings.filterwarnings("ignore")

import numpy.random as random
import statsmodels.api as sm
import statsmodels.tsa as tsa
import statsmodels.formula.api as smf

In [3]:
#Data preparation for CameraAccessory category
Master_Gaming=pd.read_csv('Master_Gaming.csv')

In [4]:
Master_Gaming.drop(["Unnamed: 0"], axis = 1, inplace = True)
Master_Gaming.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,0.0,1,0,28.0,10.0
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,0.0,1,0,29.0,12.5
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,1.0,1,0,33.0,13.5
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,0.0,1,0,33.5,14.5
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,0.550021,1.646397,0.294704,1.116378,0.121520,0.0,1,0,33.5,15.0

In [5]:
Master_Gaming.columns

Index(['Week', 'gmv_sum', 'units_sum', 'sla_mean', 'product_mrp_mean',
       'product_mrp_sum', 'product_procurement_sla_mean',
       'Weekly_Investment_Total_mean', 'Weekly_Investment_TV_mean',
       'Weekly_Investment_Digital_mean', 'Weekly_Investment_Sponsorship_mean',
       'Weekly_Investment_Content_Marketing_mean',
       'Weekly_Investment_Online_Marketing_mean',
       'Weekly_Investment_affiliates_mean', 'Weekly_Investment_SEM_mean',
       'Weekly_Investment_Radio_mean', 'Weekly_Investment_Other_mean',
       'NPS_mean', 'Pay_Day_Flag', 's1_fact.order_payment_type_sum',
       'Prepaid_Flag_sum', 'Weekly_TV_adstock_mean',
       'Weekly_Digital_adstock_mean', 'Weekly_Sponsorship_adstock_mean',
       'Weekly_Online_Marketing_adstock_mean', 'Weekly_SEM_adstock_mean',
       'Weekly_affiliates_adstock_mean', 'Sale_Flag', 'Rain_Flag', 'Snow_Flag',
       'Max Temp (°C)_max', 'Min Temp (°C)_min'],
      dtype='object')

In [6]:
Master_Gaming.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 32 columns):
Week                                        53 non-null int64
gmv_sum                                     53 non-null float64
units_sum                                   53 non-null int64
sla_mean                                    53 non-null float64
product_mrp_mean                            53 non-null float64
product_mrp_sum                             53 non-null float64
product_procurement_sla_mean                53 non-null float64
Weekly_Investment_Total_mean                53 non-null float64
Weekly_Investment_TV_mean                   53 non-null float64
Weekly_Investment_Digital_mean              53 non-null float64
Weekly_Investment_Sponsorship_mean          53 non-null float64
Weekly_Investment_Content_Marketing_mean    53 non-null float64
Weekly_Investment_Online_Marketing_mean     53 non-null float64
Weekly_Investment_affiliates_mean           53 non-null float64
Weekly_Investment_SEM_mean                  53 non-null float64
Weekly_Investment_Radio_mean                53 non-null float64
Weekly_Investment_Other_mean                53 non-null float64
NPS_mean                                    53 non-null float64
Pay_Day_Flag                                53 non-null int64
s1_fact.order_payment_type_sum              53 non-null int64
Prepaid_Flag_sum                            53 non-null int64
Weekly_TV_adstock_mean                      53 non-null float64
Weekly_Digital_adstock_mean                 53 non-null float64
Weekly_Sponsorship_adstock_mean             53 non-null float64
Weekly_Online_Marketing_adstock_mean        53 non-null float64
Weekly_SEM_adstock_mean                     53 non-null float64
Weekly_affiliates_adstock_mean              53 non-null float64
Sale_Flag                                   53 non-null float64
Rain_Flag                                   53 non-null int64
Snow_Flag                                   53 non-null int64
Max Temp (°C)_max                           53 non-null float64
Min Temp (°C)_min                           53 non-null float64
dtypes: float64(25), int64(7)
memory usage: 13.3 KB

In [7]:
Master_Gaming.describe()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min
count,53.000000,5.300000e+01,53.000000,53.000000,53.000000,5.300000e+01,53.000000,53.000000,53.000000,53.000000,...,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,27.000000,1.096253e+06,3488.301887,5.621258,1521.813873,4.981488e+06,2.424027,15.607281,0.833404,0.553283,...,1.042007,12.734375,6.674443,3.201234,2.114070,0.283019,0.792453,0.150943,21.563208,3.877358
std,15.443445,1.338988e+06,1839.475381,0.531483,524.996272,2.580226e+06,0.305519,9.643140,0.559044,0.673172,...,0.734643,6.496211,3.179000,1.900348,1.005090,0.454776,0.409432,0.361420,9.161962,9.155655
min,1.000000,0.000000e+00,1.000000,3.333333,665.666667,1.997000e+03,1.000000,0.000000,0.000000,0.100000,...,0.490000,1.060104,0.176196,1.116377,0.077180,0.000000,0.000000,0.000000,-5.000000,-18.000000
25%,14.000000,0.000000e+00,2619.000000,5.441454,1333.305963,3.745379e+06,2.333333,10.680000,0.370000,0.261998,...,0.560000,11.278469,6.404659,2.152843,2.001717,0.000000,1.000000,0.000000,16.000000,-3.500000
50%,27.000000,7.023610e+05,3601.000000,5.710865,1453.917750,5.065211e+06,2.438797,15.098494,0.860000,0.320000,...,0.706855,13.082098,8.021926,2.564067,2.570292,0.000000,1.000000,0.000000,22.500000,5.000000
75%,40.000000,2.245456e+06,4345.000000,5.890192,1618.450053,6.111755e+06,2.546188,21.390000,1.192837,0.559419,...,1.058584,14.482863,8.994342,3.860708,2.857254,1.000000,1.000000,0.000000,29.000000,13.000000
max,53.000000,6.456799e+06,10252.000000,7.000000,4999.000000,1.214914e+07,3.509259,37.810000,2.070000,2.800000,...,3.110000,26.057550,9.586060,8.063207,3.028860,1.000000,1.000000,1.000000,35.000000,18.000000

In [8]:
#Creating Promoting Pricing Effect

#Calculating percentage of discount offered.
Master_Gaming['discount_off_percent'] = ((Master_Gaming['product_mrp_mean']-Master_Gaming['gmv_sum'])/Master_Gaming['product_mrp_mean'])*100

In [9]:
Master_Gaming.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,0.0,1,0,28.0,10.0,-50848.555249
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,0.0,1,0,29.0,12.5,-166083.861760
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,1.0,1,0,33.0,13.5,-169469.991280
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,0.0,1,0,33.5,14.5,-140026.003086
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,1.646397,0.294704,1.116378,0.121520,0.0,1,0,33.5,15.0,-56312.832314

In [11]:
#Calculating List Price for all skus
Master_Gaming['list_price'] = (Master_Gaming['gmv_sum']/Master_Gaming['units_sum'])

In [12]:
Master_Gaming.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent,list_price
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,0.0,1,0,28.0,10.0,-50848.555249,835.864407
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,0.0,1,0,29.0,12.5,-166083.861760,932.697976
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,1.0,1,0,33.0,13.5,-169469.991280,815.343631
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,0.0,1,0,33.5,14.5,-140026.003086,1057.819959
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,0.294704,1.116378,0.121520,0.0,1,0,33.5,15.0,-56312.832314,1021.935549

In [13]:
week_range = range(0,52,1)

In [14]:
#Calculating Shelf Price inflation
for i in week_range:
    Master_Gaming.loc[(Master_Gaming['Week'] == i+1), 'shelf_price_infl'] = Master_Gaming.iloc[i,33]/ Master_Gaming.iloc[i-1,33]

In [15]:
Master_Gaming.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent,list_price,shelf_price_infl
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,28.0,10.0,-50848.555249,835.864407,inf
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,29.0,12.5,-166083.861760,932.697976,1.115848
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,1.116377,0.121612,1.0,1,0,33.0,13.5,-169469.991280,815.343631,0.874178
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,33.5,14.5,-140026.003086,1057.819959,1.297392
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,1.116378,0.121520,0.0,1,0,33.5,15.0,-56312.832314,1021.935549,0.966077

In [16]:
Master_Gaming['shelf_price_infl'].fillna(0,inplace=True)
Master_Gaming['shelf_price_infl'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
Name: shelf_price_infl, dtype: bool

In [17]:
Master_Gaming.loc[(Master_Gaming['shelf_price_infl'] == np.inf), 'shelf_price_infl'] = 0.0

In [331]:
Master_Camera['shelf_price_infl']

0     62.309250
1      0.858658
2      1.110759
3      0.923783
4      1.017227
5      0.396025
6      0.641172
7      0.905668
8      1.106084
9      0.983791
10     0.836751
11     0.992716
12     1.087397
13     1.036605
14     0.866963
15     1.143352
16     0.984449
17     0.890846
18     1.217744
19     0.900508
20     0.000000
21     0.000000
22     0.000000
23     0.000000
24     0.000000
25     1.258213
26     1.149719
27     1.306790
28     0.881118
29     0.781010
30     1.278259
31     0.887020
32     0.754581
33     1.504354
34     0.869282
35     0.885335
36     0.830586
37     0.286989
38     0.000000
39     0.000000
40     0.000000
41     0.000000
42     0.000000
43     0.000000
44     0.000000
45     0.000000
46     0.000000
47     1.486108
48     1.117175
49     1.090747
50     0.913094
51     0.000000
Name: shelf_price_infl, dtype: float64

In [18]:
Master_Gaming.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent,list_price,shelf_price_infl
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,28.0,10.0,-50848.555249,835.864407,0.000000
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,29.0,12.5,-166083.861760,932.697976,1.115848
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,1.116377,0.121612,1.0,1,0,33.0,13.5,-169469.991280,815.343631,0.874178
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,33.5,14.5,-140026.003086,1057.819959,1.297392
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,1.116378,0.121520,0.0,1,0,33.5,15.0,-56312.832314,1021.935549,0.966077

In [19]:
#Implementing Distributed Lag Model with LinearRegression for CameraAccessory
y = Master_Gaming.pop('gmv_sum')
X = Master_Gaming

In [20]:
import statsmodels.api as sm

# Add a constant

X_lm = sm.add_constant(X)

# Create a first fitted model
lr = sm.OLS(y, X_lm).fit()

In [21]:
print(lr.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                gmv_sum   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.996
Method:                 Least Squares   F-statistic:                     433.1
Date:                Mon, 16 Sep 2019   Prob (F-statistic):           1.79e-26
Time:                        13:30:51   Log-Likelihood:                -657.37
No. Observations:                  53   AIC:                             1373.
Df Residuals:                      24   BIC:                             1430.
Df Model:                          28
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                    -3.689e+05   1.73e+05     -2.136      0.043   -7.25e+05   -1.25e+04
Week                                      5270.7144   1.43e+04      0.368      0.716   -2.43e+04    3.48e+04
units_sum                                 -596.0597   1818.558     -0.328      0.746   -4349.378    3157.259
sla_mean                                 -8.697e+04   5.06e+04     -1.720      0.098   -1.91e+05    1.74e+04
product_mrp_mean                          -119.0065     57.624     -2.065      0.050    -237.937      -0.076
product_mrp_sum                              0.2346      0.058      4.028      0.000       0.114       0.355
product_procurement_sla_mean             -2.138e+05   1.05e+05     -2.042      0.052    -4.3e+05    2307.515
Weekly_Investment_Total_mean             -6.046e+04   4.21e+04     -1.437      0.164   -1.47e+05    2.64e+04
Weekly_Investment_TV_mean                 3.037e+05   3.97e+05      0.765      0.452   -5.16e+05    1.12e+06
Weekly_Investment_Digital_mean           -8.801e+05   4.23e+05     -2.081      0.048   -1.75e+06   -7131.630
Weekly_Investment_Sponsorship_mean        2.363e+05   9.68e+04      2.441      0.022    3.65e+04    4.36e+05
Weekly_Investment_Content_Marketing_mean  1.734e+06   8.73e+05      1.987      0.058   -6.72e+04    3.53e+06
Weekly_Investment_Online_Marketing_mean  -7.386e+05   2.46e+05     -3.007      0.006   -1.25e+06   -2.32e+05
Weekly_Investment_affiliates_mean         1.414e+06   8.41e+05      1.681      0.106   -3.22e+05    3.15e+06
Weekly_Investment_SEM_mean                1.652e+05   1.28e+05      1.293      0.208   -9.85e+04    4.29e+05
Weekly_Investment_Radio_mean             -2.537e+04   5.02e+04     -0.506      0.618   -1.29e+05    7.82e+04
Weekly_Investment_Other_mean              2.295e+04   5.21e+04      0.440      0.664   -8.47e+04    1.31e+05
NPS_mean                                  1.968e+04   6429.812      3.061      0.005    6413.895     3.3e+04
Pay_Day_Flag                             -3.075e+04   3.03e+04     -1.015      0.320   -9.33e+04    3.18e+04
s1_fact.order_payment_type_sum             271.1360   1824.108      0.149      0.883   -3493.637    4035.909
Prepaid_Flag_sum                           213.9762   1789.680      0.120      0.906   -3479.741    3907.693
Weekly_TV_adstock_mean                    3.547e+04   1.82e+05      0.195      0.847    -3.4e+05    4.11e+05
Weekly_Digital_adstock_mean              -1.754e+06   8.35e+05     -2.102      0.046   -3.48e+06   -3.18e+04
Weekly_Sponsorship_adstock_mean          -2.101e+05   1.02e+05     -2.062      0.050    -4.2e+05     237.253
Weekly_Online_Marketing_adstock_mean     -1.944e+05   2.85e+05     -0.682      0.502   -7.83e+05    3.94e+05
Weekly_SEM_adstock_mean                   1.121e+06   5.89e+05      1.905      0.069   -9.37e+04    2.34e+06
Weekly_affiliates_adstock_mean            1.154e+06   5.76e+05      2.001      0.057   -3.62e+04    2.34e+06
Sale_Flag                                -6.855e+04   4.31e+04     -1.591      0.125   -1.57e+05    2.04e+04
Rain_Flag                                -5.771e+04   4.17e+04     -1.385      0.179   -1.44e+05    2.83e+04
Snow_Flag                                 2.407e+04   5.42e+04      0.444      0.661   -8.79e+04    1.36e+05
Max Temp (°C)_max                        -3468.6807   4256.886     -0.815      0.423   -1.23e+04    5317.100
Min Temp (°C)_min                        -1152.2278   4445.278     -0.259      0.798   -1.03e+04    8022.375
discount_off_percent                       -13.9469      0.673    -20.711      0.000     -15.337     -12.557
list_price                                 903.3263    348.311      2.593      0.016     184.449    1622.204
shelf_price_infl                         -3.061e+04   4.45e+04     -0.687      0.498   -1.23e+05    6.13e+04
==============================================================================
Omnibus:                        0.801   Durbin-Watson:                   2.109
Prob(Omnibus):                  0.670   Jarque-Bera (JB):                0.812
Skew:                          -0.091   Prob(JB):                        0.666
Kurtosis:                       2.421   Cond. No.                     1.71e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.69e-18. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.