
### Working out weekly aggregated dataframes
### Feature Engineering :
#### Adstocks and KPIs
### Adding Ontario Weather data
### Obtain completed datasets for the three categories

In [253]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from matplotlib import style
sns.set(style='whitegrid',color_codes=True)

import warnings
warnings.filterwarnings("ignore")

import numpy.random as random
import statsmodels.api as sm
import statsmodels.tsa as tsa
import statsmodels.formula.api as smf

In [254]:
master_data=pd.read_csv('Master_data.csv')
master_data.drop(["Unnamed: 0",'index','pincode','cust_id','fsn_id','order_id','order_item_id'], axis = 1, inplace = True)

In [255]:
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500192 entries, 0 to 500191
Data columns (total 34 columns):
order_date                             500192 non-null object
Year                                   500192 non-null int64
Month                                  500192 non-null int64
gmv                                    500192 non-null float64
units                                  500192 non-null int64
deliverybdays                          500192 non-null float64
deliverycdays                          500192 non-null float64
s1_fact.order_payment_type             500192 non-null int64
sla                                    500192 non-null int64
product_analytic_super_category        500192 non-null object
product_analytic_category              500192 non-null object
product_analytic_sub_category          500192 non-null object
product_analytic_vertical              500192 non-null object
product_mrp                            500192 non-null float64
product_procurement_sla                500192 non-null int64
frequency_y                            500192 non-null int64
percent                                500192 non-null float64
NPS                                    500192 non-null float64
Stock Index                            500192 non-null float64
Day                                    500192 non-null int64
Week                                   500192 non-null int64
Pay_Day                                500192 non-null int64
Weekly_Investment_Total                500192 non-null float64
Weekly_Investment_TV                   500192 non-null float64
Weekly_Investment_Digital              500192 non-null float64
Weekly_Investment_Sponsorship          500192 non-null float64
Weekly_Investment_Content_Marketing    500192 non-null float64
Weekly_Investment_Online_Marketing     500192 non-null float64
Weekly_Investment_affiliates           500192 non-null float64
Weekly_Investment_SEM                  500192 non-null float64
Weekly_Investment_Radio                500192 non-null float64
Weekly_Investment_Other                500192 non-null float64
Prepaid_Flag                           500192 non-null int64
Weekday                                500192 non-null object
dtypes: float64(17), int64(11), object(6)
memory usage: 129.7+ MB

#### Creating AdStock variables from the Media data

In [256]:
data_media=pd.read_excel("C:/Users/user/Desktop/CAPSTONE/MediaData.xlsx", sheetname='Media Investment', skiprows=[0,1], usecols=range(1,13))

data_media["Year_month"]=data_media["Year"].map(str) + "-" +data_media["Month"].map(str)
data_media[["Year", "Month"]] = data_media[["Year", "Month"]].apply(pd.to_numeric)

#Replacing NA values by zero in Radio and Others investment details
data_media.fillna(0, inplace=True)

In [257]:
data_media=data_media.rename(columns = {' Affiliates':'Affiliates'})
### Incude adstock

ar_coeff = .5

TV_adstock = tsa.filters.filtertools.recursive_filter(data_media['TV'], ar_coeff)

Digital_adstock = tsa.filters.filtertools.recursive_filter(data_media['Digital'], ar_coeff)

Radio_adstock = tsa.filters.filtertools.recursive_filter(data_media['Radio'], ar_coeff)

Content_Marketing_adstock = tsa.filters.filtertools.recursive_filter(data_media['Content Marketing'], ar_coeff)

Online_marketing_adstock = tsa.filters.filtertools.recursive_filter(data_media['Online marketing'], ar_coeff)

Affiliates_adstock = tsa.filters.filtertools.recursive_filter(data_media['Affiliates'], ar_coeff)

SEM_adstock = tsa.filters.filtertools.recursive_filter(data_media['SEM'], ar_coeff)

Sponsorship_adstock=tsa.filters.filtertools.recursive_filter(data_media['Sponsorship'], ar_coeff)

In [258]:
# Concatenating
df_ad= pd.concat([data_media,TV_adstock,Digital_adstock,
                 Radio_adstock,Content_Marketing_adstock,
                 Online_marketing_adstock,Affiliates_adstock, SEM_adstock, Sponsorship_adstock],axis=1)

In [259]:
data_media[['TV_adstock','Digital_adstock',
                 'Radio_adstock','Content_Marketing_adstock',
                 'Online_marketing_adstock','Affiliates_adstock','SEM_adstock','Sponsorship_adstock']]=pd.concat([TV_adstock,Digital_adstock,
                 Radio_adstock,Content_Marketing_adstock,
                 Online_marketing_adstock,Affiliates_adstock, SEM_adstock, Sponsorship_adstock],axis=1)
data_media[['Month','TV_adstock','Digital_adstock',
                 'Radio_adstock','Content_Marketing_adstock',
                 'Online_marketing_adstock','Affiliates_adstock','SEM_adstock','Sponsorship_adstock']]

,Month,TV_adstock,Digital_adstock,Radio_adstock,Content_Marketing_adstock,Online_marketing_adstock,Affiliates_adstock,SEM_adstock,Sponsorship_adstock
0,7,0.215330,2.533014,0.000000,0.000933,1.327278,0.547254,5.023697,7.414270
1,8,0.114103,2.544581,0.000000,0.000473,0.792883,0.347311,5.025377,4.770467
2,9,3.936555,2.628818,0.000000,0.610528,16.776432,5.211922,8.714837,65.172885
3,10,8.112989,13.936889,0.000000,3.749339,32.759993,9.579672,36.284430,117.258974
4,11,8.277124,8.243913,0.000000,2.043303,35.941571,11.385603,23.364247,72.801603
5,12,9.536064,7.185317,0.000000,2.088958,40.474541,12.519739,22.863154,93.106220
6,1,9.148032,4.048658,2.700000,1.944479,43.137271,13.629870,15.631577,50.753110
7,2,7.160024,3.936980,1.350000,1.569011,41.461002,13.279954,12.689418,37.102110
8,3,12.880012,4.068490,1.545000,1.154505,39.168319,12.857644,11.538300,60.141055
9,4,11.645202,2.906137,0.772500,0.612128,36.098669,12.122278,9.989108,54.378881
10,5,7.192601,2.223069,1.486250,1.096064,41.699335,12.861139,11.904554,58.869441
11,6,5.259017,2.532295,0.743125,0.593113,28.820967,9.198592,9.687793,54.483261

In [260]:
# Generating some significant adstock values
master_data['Weekly_TV_adstock'] = 0.00
master_data['Weekly_Digital_adstock'] = 0.00
master_data['Weekly_Sponsorship_adstock'] = 0.00
master_data['Weekly_Online_Marketing_adstock'] = 0.00
master_data['Weekly_affiliates_adstock'] = 0.00
master_data['Weekly_SEM_adstock'] = 0.00


# Weekly investment = (Investment for that month) / 4.5¶
k=data_media[['Month','TV_adstock','Digital_adstock',
                 'Online_marketing_adstock','Affiliates_adstock','SEM_adstock','Sponsorship_adstock']]/4.5

#TV investment

master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 1), 'Weekly_TV_adstock'] = 2.03
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 2), 'Weekly_TV_adstock'] = 1.59
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 3), 'Weekly_TV_adstock'] = 2.86
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 4), 'Weekly_TV_adstock'] = 2.58
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 5), 'Weekly_TV_adstock'] = 1.59
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 6), 'Weekly_TV_adstock'] = 1.16
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 7), 'Weekly_TV_adstock'] = 0.04
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 9), 'Weekly_TV_adstock'] = 0.025
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 10), 'Weekly_TV_adstock'] = 0.86
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 11), 'Weekly_TV_adstock'] = 1.83
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 12), 'Weekly_TV_adstock'] = 2.1


#Digital investment

master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 1), 'Weekly_Digital_adstock'] = 0.89
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 2), 'Weekly_Digital_adstock'] = 0.87
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 3), 'Weekly_Digital_adstock'] = 0.90
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 4), 'Weekly_Digital_adstock'] = 0.64
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 5), 'Weekly_Digital_adstock'] = 0.49
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 6), 'Weekly_Digital_adstock'] = 0.56
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 7), 'Weekly_Digital_adstock'] = 0.55
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 8), 'Weekly_Digital_adstock'] = 0.56
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 9), 'Weekly_Digital_adstock'] = 0.58
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 10), 'Weekly_Digital_adstock'] = 3.11
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 11), 'Weekly_Digital_adstock'] = 1.8
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 12), 'Weekly_Digital_adstock'] = 1.59


#Sponsorship investment

master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 1), 'Weekly_Sponsorship_adstock'] = k.iloc[6,6]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 2), 'Weekly_Sponsorship_adstock'] = k.iloc[7,6]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 3), 'Weekly_Sponsorship_adstock'] = k.iloc[8,6]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 4), 'Weekly_Sponsorship_adstock'] = k.iloc[9,6]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 5), 'Weekly_Sponsorship_adstock'] = k.iloc[10,6]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 6), 'Weekly_Sponsorship_adstock'] = k.iloc[11,6]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 7), 'Weekly_Sponsorship_adstock'] = k.iloc[0,6]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 8), 'Weekly_Sponsorship_adstock'] = k.iloc[1,6]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 9), 'Weekly_Sponsorship_adstock'] = k.iloc[2,6]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 10), 'Weekly_Sponsorship_adstock'] =k.iloc[3,6]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 11), 'Weekly_Sponsorship_adstock'] = k.iloc[4,6]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 12), 'Weekly_Sponsorship_adstock'] = k.iloc[5,6]





# Online marketing investment

master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 1), 'Weekly_Online_Marketing_adstock'] = k.iloc[6,3]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 2), 'Weekly_Online_Marketing_adstock'] = k.iloc[7,3]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 3), 'Weekly_Online_Marketing_adstock'] = k.iloc[8,3]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 4), 'Weekly_Online_Marketing_adstock'] = k.iloc[9,3]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 5), 'Weekly_Online_Marketing_adstock'] = k.iloc[10,3]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 6), 'Weekly_Online_Marketing_adstock'] = k.iloc[11,3]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 7), 'Weekly_Online_Marketing_adstock'] = k.iloc[0,3]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 8), 'Weekly_Online_Marketing_adstock'] = k.iloc[1,3]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 9), 'Weekly_Online_Marketing_adstock'] = k.iloc[2,3]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 10), 'Weekly_Online_Marketing_adstock'] =k.iloc[3,3]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 11), 'Weekly_Online_Marketing_adstock'] =k.iloc[4,3]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 12), 'Weekly_Online_Marketing_adstock'] =k.iloc[5,3]



# Affiliates investment

master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 1), 'Weekly_affiliates_adstock'] = k.iloc[6,4]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 2), 'Weekly_affiliates_adstock'] = k.iloc[7,4]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 3), 'Weekly_affiliates_adstock'] = k.iloc[8,4]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 4), 'Weekly_affiliates_adstock'] = k.iloc[9,4]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 5), 'Weekly_affiliates_adstock'] = k.iloc[10,4]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 6), 'Weekly_affiliates_adstock'] = k.iloc[11,4]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 7), 'Weekly_affiliates_adstock'] = k.iloc[0,4]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 8), 'Weekly_affiliates_adstock'] = k.iloc[1,4]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 9), 'Weekly_affiliates_adstock'] = k.iloc[2,4] 
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 10), 'Weekly_affiliates_adstock'] = k.iloc[3,4]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 11), 'Weekly_affiliates_adstock'] = k.iloc[4,4]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 12), 'Weekly_affiliates_adstock'] = k.iloc[5,4]



#SEM investment

master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 1), 'Weekly_SEM_adstock'] = k.iloc[6,5]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 2), 'Weekly_SEM_adstock'] = k.iloc[7,5]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 3), 'Weekly_SEM_adstock'] = k.iloc[8,5]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 4), 'Weekly_SEM_adstock'] = k.iloc[9,5]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 5), 'Weekly_SEM_adstock'] = k.iloc[10,5]
master_data.loc[(master_data['Year'] == 2016) & (master_data['Month'] == 6), 'Weekly_SEM_adstock'] = k.iloc[11,5]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 7), 'Weekly_SEM_adstock'] = k.iloc[0,5]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 8), 'Weekly_SEM_adstock'] = k.iloc[1,5]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 9), 'Weekly_SEM_adstock'] = k.iloc[2,5]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 10), 'Weekly_SEM_adstock'] = k.iloc[3,5]
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 11), 'Weekly_SEM_adstock'] =k.iloc[4,5] 
master_data.loc[(master_data['Year'] == 2015) & (master_data['Month'] == 12), 'Weekly_SEM_adstock'] =k.iloc[5,5]

In [261]:
df1=master_data.product_analytic_sub_category.str.contains('CameraAccessory')
CameraAccessory=master_data[df1]

df2=master_data.product_analytic_sub_category.str.contains('GamingAccessory')
GamingAccessory=master_data[df2]

df3=master_data.product_analytic_sub_category.str.contains('HomeAudio')
HomeAudio=master_data[df3]

#### Creating weekly aggregated data for Camera Accessory

In [262]:
CameraAccessory.head()

,order_date,Year,Month,gmv,units,deliverybdays,deliverycdays,s1_fact.order_payment_type,sla,product_analytic_super_category,...,Weekly_Investment_Radio,Weekly_Investment_Other,Prepaid_Flag,Weekday,Weekly_TV_adstock,Weekly_Digital_adstock,Weekly_Sponsorship_adstock,Weekly_Online_Marketing_adstock,Weekly_affiliates_adstock,Weekly_SEM_adstock
0,2015-10-17 15:11:54,2015,10,6400.0,1,0.0,0.0,1,5,CE,...,0.0,0.0,0,Saturday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
1,2015-10-19 10:07:22,2015,10,6900.0,1,0.0,0.0,1,7,CE,...,0.0,0.0,0,Monday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
2,2015-10-20 15:45:56,2015,10,1990.0,1,0.0,0.0,1,10,CE,...,0.0,0.0,0,Tuesday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
3,2015-10-14 12:05:15,2015,10,1690.0,1,0.0,0.0,0,4,CE,...,0.0,0.0,1,Wednesday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
4,2015-10-17 21:25:03,2015,10,1618.0,1,0.0,0.0,0,6,CE,...,0.0,0.0,1,Saturday,0.86,3.11,26.05755,7.279999,2.128816,8.063207

In [263]:
# Selecting the columns and aggregate functions
aggregates = {'gmv': ['sum'], 'units': ['sum'], 'sla': ['mean'], 'product_mrp': ['mean','sum'],
              'product_procurement_sla':['mean'], 'Weekly_Investment_Total':['mean'], 'Weekly_Investment_TV':['mean'],
              'Weekly_Investment_Digital':['mean'], 'Weekly_Investment_Sponsorship':['mean'],
              'Weekly_Investment_Content_Marketing':['mean'], 'Weekly_Investment_Online_Marketing':['mean'],
              'Weekly_Investment_affiliates':['mean'], 'Weekly_Investment_SEM':['mean'], 'Weekly_Investment_Radio':['mean'],
              'Weekly_Investment_Other':['mean'], 'NPS':['mean'], 'Pay_Day':['sum'],
              's1_fact.order_payment_type':['sum'], 'Prepaid_Flag':['sum'],'Weekly_TV_adstock':['mean'],
              'Weekly_Digital_adstock':['mean'], 'Weekly_Sponsorship_adstock':['mean'], 'Weekly_Online_Marketing_adstock':['mean'], 
              'Weekly_SEM_adstock':['mean'], 'Weekly_affiliates_adstock':['mean']}
CameraAccessory_Weekly = CameraAccessory.groupby('Week').agg(aggregates)

CameraAccessory_Weekly.columns = ['_'.join(col) for col in CameraAccessory_Weekly.columns.values]

In [264]:
CameraAccessory_Weekly.reset_index(level=0, inplace=True)
print(CameraAccessory_Weekly.shape)

(52, 27)

In [265]:
CameraAccessory_Weekly.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,NPS_mean,Pay_Day_sum,s1_fact.order_payment_type_sum,Prepaid_Flag_sum,Weekly_TV_adstock_mean,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean
0,1,687143.0,523,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,54.599588,0,327,188,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
1,2,3449874.0,3058,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,54.599588,0,1999,978,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
2,3,3834486.0,3060,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,54.599588,491,1962,1038,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
3,4,3359335.0,2902,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,54.599588,0,1941,895,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
4,5,1443658.0,1226,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,54.608590,0,849,348,0.039933,0.550017,1.646634,0.294752,1.116378,0.121538

#### Creating weekly aggregated data for Gaming Accesory

In [266]:
GamingAccessory.head()

,order_date,Year,Month,gmv,units,deliverybdays,deliverycdays,s1_fact.order_payment_type,sla,product_analytic_super_category,...,Weekly_Investment_Radio,Weekly_Investment_Other,Prepaid_Flag,Weekday,Weekly_TV_adstock,Weekly_Digital_adstock,Weekly_Sponsorship_adstock,Weekly_Online_Marketing_adstock,Weekly_affiliates_adstock,Weekly_SEM_adstock
209492,2015-10-04 19:24:36,2015,10,3075.0,1,0.0,0.0,1,9,CE,...,0.0,0.0,0,Sunday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
209493,2015-10-14 22:54:54,2015,10,2750.0,1,0.0,0.0,1,7,CE,...,0.0,0.0,0,Wednesday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
209494,2015-10-15 20:19:38,2015,10,2899.0,1,0.0,0.0,0,5,CE,...,0.0,0.0,1,Thursday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
209495,2015-10-17 18:21:43,2015,10,2609.0,1,0.0,0.0,0,5,CE,...,0.0,0.0,1,Saturday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
209496,2015-10-26 17:49:39,2015,10,2772.0,1,0.0,0.0,0,5,CE,...,0.0,0.0,1,Monday,0.86,3.11,26.05755,7.279999,2.128816,8.063207

In [267]:
# Selecting the columns and aggregate functions
aggregates = {'gmv': ['sum'], 'units': ['sum'], 'sla': ['mean'], 'product_mrp': ['mean','sum'],
              'product_procurement_sla':['mean'], 'Weekly_Investment_Total':['mean'], 'Weekly_Investment_TV':['mean'],
              'Weekly_Investment_Digital':['mean'], 'Weekly_Investment_Sponsorship':['mean'],
              'Weekly_Investment_Content_Marketing':['mean'], 'Weekly_Investment_Online_Marketing':['mean'],
              'Weekly_Investment_affiliates':['mean'], 'Weekly_Investment_SEM':['mean'], 'Weekly_Investment_Radio':['mean'],
              'Weekly_Investment_Other':['mean'], 'NPS':['mean'], 'Pay_Day':['sum'],
              's1_fact.order_payment_type':['sum'], 'Prepaid_Flag':['sum'],'Weekly_TV_adstock':['mean'],
              'Weekly_Digital_adstock':['mean'], 'Weekly_Sponsorship_adstock':['mean'], 'Weekly_Online_Marketing_adstock':['mean'], 
              'Weekly_SEM_adstock':['mean'], 'Weekly_affiliates_adstock':['mean']}
GamingAccessory_Weekly = GamingAccessory.groupby('Week').agg(aggregates)

GamingAccessory_Weekly.columns = ['_'.join(col) for col in GamingAccessory_Weekly.columns.values]

In [268]:
GamingAccessory_Weekly.reset_index(level=0, inplace=True)
print(GamingAccessory_Weekly.shape)
GamingAccessory_Weekly.head()

(53, 27)

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,NPS_mean,Pay_Day_sum,s1_fact.order_payment_type_sum,Prepaid_Flag_sum,Weekly_TV_adstock_mean,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,54.599588,3,582,282,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,54.599588,0,1954,607,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,54.599588,308,2024,648,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,54.599588,0,1842,510,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,54.610766,1,761,203,0.039917,0.550021,1.646397,0.294704,1.116378,0.121520

#### Creating weekly level aggregated data for Home Audio

In [269]:
HomeAudio.head()

,order_date,Year,Month,gmv,units,deliverybdays,deliverycdays,s1_fact.order_payment_type,sla,product_analytic_super_category,...,Weekly_Investment_Radio,Weekly_Investment_Other,Prepaid_Flag,Weekday,Weekly_TV_adstock,Weekly_Digital_adstock,Weekly_Sponsorship_adstock,Weekly_Online_Marketing_adstock,Weekly_affiliates_adstock,Weekly_SEM_adstock
390526,2015-10-03 20:35:30,2015,10,7049.0,1,0.0,0.0,0,5,CE,...,0.0,0.0,1,Saturday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
390527,2015-10-16 09:03:09,2015,10,5489.0,1,0.0,0.0,0,2,CE,...,0.0,0.0,1,Friday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
390528,2015-10-16 21:55:31,2015,10,6255.0,1,0.0,0.0,0,9,CE,...,0.0,0.0,1,Friday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
390529,2015-10-16 23:25:07,2015,10,6099.0,1,0.0,0.0,0,3,CE,...,0.0,0.0,1,Friday,0.86,3.11,26.05755,7.279999,2.128816,8.063207
390530,2015-10-20 17:42:59,2015,10,6850.0,1,0.0,0.0,1,9,CE,...,0.0,0.0,0,Tuesday,0.86,3.11,26.05755,7.279999,2.128816,8.063207

In [270]:
# Selecting the columns and aggregate functions
aggregates = {'gmv': ['sum'], 'units': ['sum'], 'sla': ['mean'], 'product_mrp': ['mean','sum'],
              'product_procurement_sla':['mean'], 'Weekly_Investment_Total':['mean'], 'Weekly_Investment_TV':['mean'],
              'Weekly_Investment_Digital':['mean'], 'Weekly_Investment_Sponsorship':['mean'],
              'Weekly_Investment_Content_Marketing':['mean'], 'Weekly_Investment_Online_Marketing':['mean'],
              'Weekly_Investment_affiliates':['mean'], 'Weekly_Investment_SEM':['mean'], 'Weekly_Investment_Radio':['mean'],
              'Weekly_Investment_Other':['mean'], 'NPS':['mean'], 'Pay_Day':['sum'],
              's1_fact.order_payment_type':['sum'], 'Prepaid_Flag':['sum'],'Weekly_TV_adstock':['mean'],
              'Weekly_Digital_adstock':['mean'], 'Weekly_Sponsorship_adstock':['mean'], 'Weekly_Online_Marketing_adstock':['mean'], 
              'Weekly_SEM_adstock':['mean'], 'Weekly_affiliates_adstock':['mean']}
HomeAudio_Weekly = HomeAudio.groupby('Week').agg(aggregates)

HomeAudio_Weekly.columns = ['_'.join(col) for col in HomeAudio_Weekly.columns.values]

In [271]:
HomeAudio_Weekly.reset_index(level=0, inplace=True)
print(HomeAudio_Weekly.shape)
HomeAudio_Weekly.head()

(50, 27)

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,NPS_mean,Pay_Day_sum,s1_fact.order_payment_type_sum,Prepaid_Flag_sum,Weekly_TV_adstock_mean,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean
0,1,8.941600e+05,389,6.325581,3586.113695,1387826.0,2.824289,0.000000,0.050000,0.560000,...,54.599588,3,281,106,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
1,2,4.780028e+06,2260,6.829485,3318.915631,7474198.0,2.813499,0.000000,0.050000,0.560000,...,54.599588,0,1679,573,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
2,3,5.002346e+06,2316,6.766522,3528.674348,8115951.0,2.794348,0.000000,0.050000,0.560000,...,54.599588,329,1764,536,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
3,4,4.218112e+06,2095,6.836695,3311.164745,6893845.0,2.822286,0.000000,0.050000,0.560000,...,54.599588,0,1641,441,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612
4,5,2.002045e+06,946,7.063830,3483.221277,3274228.0,2.669149,0.001202,0.049947,0.559702,...,54.605319,0,717,223,0.039957,0.550011,1.646990,0.294824,1.116378,0.121565

#### Adding Sales flag to these 3 dataframes

In [272]:
data_special_sale=pd.read_excel("C:/Users/user/Desktop/CAPSTONE/MediaData.xlsx", sheetname='Special Sale Calendar', skiprows=[0,1,14,15],index_col=0, header=None)

data_special_sale.reset_index(drop=True,inplace=True)
data_special_sale.columns=['Year','special_sales']
data_special_sale.iloc[0:6,0:1]=2015
data_special_sale.iloc[6:,0:1]=2016

#Deriving Manually
data_special_sale['sales_start_week']=[3,7,9,16,19,26,30,32,34,33,37,48]
data_special_sale['sales_end_week']=[3,8,9,16,20,27,30,32,34,34,37,48]
data_special_sale

      Year                special_sales  sales_start_week  sales_end_week
0   2015.0               (18-19th July)                 3               3
1   2015.0                (15-17th Aug)                 7               8
2   2015.0                (28-30th Aug)                 9               9
3   2015.0                (17-15th Oct)                16              16
4   2015.0                 (7-14th Nov)                19              20
5   2015.0   (25th Dec'15 - 3rd Jan'16)                26              27
6   2016.0                  (20-22 Jan)                30              30
7   2016.0                    (1-2 Feb)                32              32
8   2016.0                  (20-21 Feb)                34              34
9   2016.0                  (14-15 Feb)                33              34
10  2016.0                    (7-9 Mar)                37              37
11  2016.0                  (25-27 May)                48              48

In [273]:

CameraAccessory_Weekly['Sale_Flag'] = 0.00
CameraAccessory_Weekly.loc[(CameraAccessory_Weekly['Week'].isin(['3','7', '9','8','16','19','20','26','27','30','32','34','33','37','48'])), 'Sale_Flag'] = 1

GamingAccessory_Weekly['Sale_Flag'] = 0.00
GamingAccessory_Weekly.loc[(GamingAccessory_Weekly['Week'].isin(['3','7', '9','8','16','19','20','26','27','30','32','34','33','37','48'])), 'Sale_Flag'] = 1

HomeAudio_Weekly['Sale_Flag'] = 0.00
HomeAudio_Weekly.loc[(HomeAudio_Weekly['Week'].isin(['3','7', '9','8','16','19','20','26','27','30','32','34','33','37','48'])), 'Sale_Flag'] = 1

In [274]:
Master_Camera.columns

Index(['Week', 'gmv_sum', 'units_sum', 'sla_mean', 'product_mrp_mean',
       'product_mrp_sum', 'product_procurement_sla_mean',
       'Weekly_Investment_Total_mean', 'Weekly_Investment_TV_mean',
       'Weekly_Investment_Digital_mean', 'Weekly_Investment_Sponsorship_mean',
       'Weekly_Investment_Content_Marketing_mean',
       'Weekly_Investment_Online_Marketing_mean',
       'Weekly_Investment_affiliates_mean', 'Weekly_Investment_SEM_mean',
       'Weekly_Investment_Radio_mean', 'Weekly_Investment_Other_mean',
       'NPS_mean', 'Pay_Day_Flag', 's1_fact.order_payment_type_sum',
       'Prepaid_Flag_sum', 'Weekly_TV_adstock_mean',
       'Weekly_Digital_adstock_mean', 'Weekly_Sponsorship_adstock_mean',
       'Weekly_Online_Marketing_adstock_mean', 'Weekly_SEM_adstock_mean',
       'Weekly_affiliates_adstock_mean', 'Sale_Flag', 'Rain_Flag', 'Snow_Flag',
       'Max Temp (°C)_max', 'Min Temp (°C)_min'],
      dtype='object')

In [275]:
CameraAccessory_Weekly.loc[(CameraAccessory_Weekly['Pay_Day_sum'] != 0), 'Pay_Day_sum'] = 1
GamingAccessory_Weekly.loc[(GamingAccessory_Weekly['Pay_Day_sum'] != 0), 'Pay_Day_sum'] = 1
HomeAudio_Weekly.loc[(HomeAudio_Weekly['Pay_Day_sum'] != 0), 'Pay_Day_sum'] = 1
CameraAccessory_Weekly.rename(columns={'Pay_Day_sum':'Pay_Day_Flag'}, inplace=True)
GamingAccessory_Weekly.rename(columns={'Pay_Day_sum':'Pay_Day_Flag'}, inplace=True)
HomeAudio_Weekly.rename(columns={'Pay_Day_sum':'Pay_Day_Flag'}, inplace=True)

In [276]:
CameraAccessory_Weekly.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Pay_Day_Flag,s1_fact.order_payment_type_sum,Prepaid_Flag_sum,Weekly_TV_adstock_mean,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag
0,1,687143.0,523,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,0,327,188,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
1,2,3449874.0,3058,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,0,1999,978,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
2,3,3834486.0,3060,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,1,1962,1038,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,1.0
3,4,3359335.0,2902,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,0,1941,895,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
4,5,1443658.0,1226,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,0,849,348,0.039933,0.550017,1.646634,0.294752,1.116378,0.121538,0.0

In [277]:
GamingAccessory_Weekly.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Pay_Day_Flag,s1_fact.order_payment_type_sum,Prepaid_Flag_sum,Weekly_TV_adstock_mean,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag
0,1,7.397400e+05,885,4.212963,1451.935185,1254472.0,3.509259,0.000000,0.050000,0.560000,...,1,582,282,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
1,2,2.442736e+06,2619,5.983991,1469.899649,3764413.0,2.843811,0.000000,0.050000,0.560000,...,0,1954,607,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
2,3,2.245456e+06,2754,5.175898,1324.206213,3538279.0,2.609281,0.000000,0.050000,0.560000,...,1,2024,648,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,1.0
3,4,2.570502e+06,2430,5.433673,1834.422194,4314561.0,2.359694,0.000000,0.050000,0.560000,...,0,1842,510,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
4,5,1.014782e+06,993,5.909751,1798.849585,1734091.0,2.438797,0.002344,0.049896,0.559419,...,1,761,203,0.039917,0.550021,1.646397,0.294704,1.116378,0.121520,0.0

In [278]:
HomeAudio_Weekly.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Pay_Day_Flag,s1_fact.order_payment_type_sum,Prepaid_Flag_sum,Weekly_TV_adstock_mean,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag
0,1,8.941600e+05,389,6.325581,3586.113695,1387826.0,2.824289,0.000000,0.050000,0.560000,...,1,281,106,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
1,2,4.780028e+06,2260,6.829485,3318.915631,7474198.0,2.813499,0.000000,0.050000,0.560000,...,0,1679,573,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
2,3,5.002346e+06,2316,6.766522,3528.674348,8115951.0,2.794348,0.000000,0.050000,0.560000,...,1,1764,536,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,1.0
3,4,4.218112e+06,2095,6.836695,3311.164745,6893845.0,2.822286,0.000000,0.050000,0.560000,...,0,1641,441,0.040000,0.550000,1.647615,0.294951,1.116377,0.121612,0.0
4,5,2.002045e+06,946,7.063830,3483.221277,3274228.0,2.669149,0.001202,0.049947,0.559702,...,0,717,223,0.039957,0.550011,1.646990,0.294824,1.116378,0.121565,0.0

#### Preparing the macronomic data

In [279]:
Weather_2016 = pd.read_csv('ONTARIO-2016.csv', skiprows=24)
Weather_2015 = pd.read_csv('ONTARIO-2015.csv', skiprows=24)

In [280]:
Weather_2016['Date/Time'] = pd.to_datetime(Weather_2016['Date/Time'])
Weather_2015['Date/Time'] = pd.to_datetime(Weather_2015['Date/Time'])

In [281]:
# Introducing Week level data
import math
from datetime import date
origin = date(2015, 7, 1)

def week_number_from(my_date, origin):
    return math.floor((my_date - origin).days / 7 + 1)
Weather_2015['Week'] = Weather_2015['Date/Time'].apply(lambda x : week_number_from(x.date(), origin))
Weather_2016['Week'] = Weather_2016['Date/Time'].apply(lambda x : week_number_from(x.date(), origin))

In [282]:
Weather = pd.concat([Weather_2015, Weather_2016], ignore_index=True)

In [283]:
#Criteria 1: Use the data from July 2015 to June 2016
Weather['Date/Time']= pd.to_datetime(Weather['Date/Time'], errors='coerce')
mask = (Weather['Date/Time'] >= '2015-07-01') & (Weather['Date/Time'] <= '2016-06-30')
Weather= Weather.loc[mask]
Weather.head(5)

,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),...,Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag,Week
181,2015-07-01,2015,7,1,†,24.5,NaN,17.0,NaN,20.8,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1
182,2015-07-02,2015,7,2,†,24.0,NaN,14.0,NaN,19.0,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1
183,2015-07-03,2015,7,3,†,25.0,NaN,10.0,NaN,17.5,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1
184,2015-07-04,2015,7,4,†,26.0,NaN,11.0,NaN,18.5,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1
185,2015-07-05,2015,7,5,†,28.0,NaN,14.0,NaN,21.0,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1

In [284]:
# Adding binary flags
Weather['Rain_Flag'] = 0
Weather['Snow_Flag'] = 0
Weather['Total Rain (mm)'].fillna(0, inplace=True)
Weather['Total Snow (cm)'].fillna(0, inplace=True)
Weather.loc[(Weather['Total Rain (mm)'] != 0), 'Rain_Flag'] = 1
Weather.loc[(Weather['Total Snow (cm)'] != 0), 'Snow_Flag'] = 1

In [285]:
# Aggregating weekly
aggregates = {'Rain_Flag': ['sum'], 'Snow_Flag': ['sum'], 'Max Temp (°C)': ['max'], 'Min Temp (°C)': ['min']}
Weather_weekly = Weather.groupby('Week').agg(aggregates)

# Renaming columns
Weather_weekly.columns = ['_'.join(col) for col in Weather_weekly.columns.values]

In [286]:
Weather_weekly.reset_index(level=0, inplace=True)

In [287]:
# Creating flags
Weather_weekly.loc[(Weather_weekly['Rain_Flag_sum'] != 0), 'Rain_Flag_sum'] = 1

Weather_weekly.loc[(Weather_weekly['Snow_Flag_sum'] != 0), 'Snow_Flag_sum'] = 1

In [288]:
Weather_weekly.rename(columns={'Rain_Flag_sum':'Rain_Flag'}, inplace=True)
Weather_weekly.rename(columns={'Snow_Flag_sum':'Snow_Flag'}, inplace=True)

In [289]:
#Merging and analysing
Master_Camera = pd.merge(CameraAccessory_Weekly, Weather_weekly, on='Week', how='outer')
Master_Gaming = pd.merge(GamingAccessory_Weekly, Weather_weekly, on='Week', how='outer')
Master_Home = pd.merge(HomeAudio_Weekly, Weather_weekly, on='Week', how='outer')

In [290]:
Master_Camera = Master_Camera[Master_Camera['gmv_sum'].notnull()] # Removing the null values

In [291]:
Master_Gaming = Master_Gaming[Master_Gaming['gmv_sum'].notnull()]
Master_Home = Master_Home[Master_Home['gmv_sum'].notnull()]

In [292]:
# Imputing the missing value with mean of previous and next day
Master_Camera.iloc[2,-1] = 13.5
Master_Gaming.iloc[2,-1] = 13.5
Master_Home.iloc[2,-1] = 13.5

In [293]:
Master_Camera.iloc[25,-1]=-8
Master_Camera.iloc[25,-2]=13.35

In [294]:
Master_Gaming.iloc[26,-1]=-8
Master_Gaming.iloc[26,-2]=13.35

In [295]:
Master_Home.iloc[23,-2]=13.35
Master_Home.iloc[23,-1]=-8.0

In [296]:
Master_Camera.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52 entries, 0 to 51
Data columns (total 32 columns):
Week                                        52 non-null int64
gmv_sum                                     52 non-null float64
units_sum                                   52 non-null float64
sla_mean                                    52 non-null float64
product_mrp_mean                            52 non-null float64
product_mrp_sum                             52 non-null float64
product_procurement_sla_mean                52 non-null float64
Weekly_Investment_Total_mean                52 non-null float64
Weekly_Investment_TV_mean                   52 non-null float64
Weekly_Investment_Digital_mean              52 non-null float64
Weekly_Investment_Sponsorship_mean          52 non-null float64
Weekly_Investment_Content_Marketing_mean    52 non-null float64
Weekly_Investment_Online_Marketing_mean     52 non-null float64
Weekly_Investment_affiliates_mean           52 non-null float64
Weekly_Investment_SEM_mean                  52 non-null float64
Weekly_Investment_Radio_mean                52 non-null float64
Weekly_Investment_Other_mean                52 non-null float64
NPS_mean                                    52 non-null float64
Pay_Day_Flag                                52 non-null float64
s1_fact.order_payment_type_sum              52 non-null float64
Prepaid_Flag_sum                            52 non-null float64
Weekly_TV_adstock_mean                      52 non-null float64
Weekly_Digital_adstock_mean                 52 non-null float64
Weekly_Sponsorship_adstock_mean             52 non-null float64
Weekly_Online_Marketing_adstock_mean        52 non-null float64
Weekly_SEM_adstock_mean                     52 non-null float64
Weekly_affiliates_adstock_mean              52 non-null float64
Sale_Flag                                   52 non-null float64
Rain_Flag                                   52 non-null int64
Snow_Flag                                   52 non-null int64
Max Temp (°C)_max                           52 non-null float64
Min Temp (°C)_min                           52 non-null float64
dtypes: float64(29), int64(3)
memory usage: 13.4 KB

In [297]:
Master_Gaming.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 0 to 52
Data columns (total 32 columns):
Week                                        53 non-null int64
gmv_sum                                     53 non-null float64
units_sum                                   53 non-null int64
sla_mean                                    53 non-null float64
product_mrp_mean                            53 non-null float64
product_mrp_sum                             53 non-null float64
product_procurement_sla_mean                53 non-null float64
Weekly_Investment_Total_mean                53 non-null float64
Weekly_Investment_TV_mean                   53 non-null float64
Weekly_Investment_Digital_mean              53 non-null float64
Weekly_Investment_Sponsorship_mean          53 non-null float64
Weekly_Investment_Content_Marketing_mean    53 non-null float64
Weekly_Investment_Online_Marketing_mean     53 non-null float64
Weekly_Investment_affiliates_mean           53 non-null float64
Weekly_Investment_SEM_mean                  53 non-null float64
Weekly_Investment_Radio_mean                53 non-null float64
Weekly_Investment_Other_mean                53 non-null float64
NPS_mean                                    53 non-null float64
Pay_Day_Flag                                53 non-null int64
s1_fact.order_payment_type_sum              53 non-null int64
Prepaid_Flag_sum                            53 non-null int64
Weekly_TV_adstock_mean                      53 non-null float64
Weekly_Digital_adstock_mean                 53 non-null float64
Weekly_Sponsorship_adstock_mean             53 non-null float64
Weekly_Online_Marketing_adstock_mean        53 non-null float64
Weekly_SEM_adstock_mean                     53 non-null float64
Weekly_affiliates_adstock_mean              53 non-null float64
Sale_Flag                                   53 non-null float64
Rain_Flag                                   53 non-null int64
Snow_Flag                                   53 non-null int64
Max Temp (°C)_max                           53 non-null float64
Min Temp (°C)_min                           53 non-null float64
dtypes: float64(25), int64(7)
memory usage: 13.7 KB

In [298]:
Master_Home.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 32 columns):
Week                                        50 non-null int64
gmv_sum                                     50 non-null float64
units_sum                                   50 non-null float64
sla_mean                                    50 non-null float64
product_mrp_mean                            50 non-null float64
product_mrp_sum                             50 non-null float64
product_procurement_sla_mean                50 non-null float64
Weekly_Investment_Total_mean                50 non-null float64
Weekly_Investment_TV_mean                   50 non-null float64
Weekly_Investment_Digital_mean              50 non-null float64
Weekly_Investment_Sponsorship_mean          50 non-null float64
Weekly_Investment_Content_Marketing_mean    50 non-null float64
Weekly_Investment_Online_Marketing_mean     50 non-null float64
Weekly_Investment_affiliates_mean           50 non-null float64
Weekly_Investment_SEM_mean                  50 non-null float64
Weekly_Investment_Radio_mean                50 non-null float64
Weekly_Investment_Other_mean                50 non-null float64
NPS_mean                                    50 non-null float64
Pay_Day_Flag                                50 non-null float64
s1_fact.order_payment_type_sum              50 non-null float64
Prepaid_Flag_sum                            50 non-null float64
Weekly_TV_adstock_mean                      50 non-null float64
Weekly_Digital_adstock_mean                 50 non-null float64
Weekly_Sponsorship_adstock_mean             50 non-null float64
Weekly_Online_Marketing_adstock_mean        50 non-null float64
Weekly_SEM_adstock_mean                     50 non-null float64
Weekly_affiliates_adstock_mean              50 non-null float64
Sale_Flag                                   50 non-null float64
Rain_Flag                                   50 non-null int64
Snow_Flag                                   50 non-null int64
Max Temp (°C)_max                           50 non-null float64
Min Temp (°C)_min                           50 non-null float64
dtypes: float64(29), int64(3)
memory usage: 12.9 KB

#### Hence, Now we have no null values

### Save the files for modelling in a different notebook (File - 3,4,5)

In [299]:
Master_Camera.to_csv('Master_Camera.csv')
Master_Gaming.to_csv('Master_Gaming.csv')
Master_Home.to_csv('Master_Home.csv')