In [316]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from matplotlib import style
sns.set(style='whitegrid',color_codes=True)

import warnings
warnings.filterwarnings("ignore")

import numpy.random as random
import statsmodels.api as sm
import statsmodels.tsa as tsa
import statsmodels.formula.api as smf

In [317]:
#Data preparation for CameraAccessory category
Master_Camera=pd.read_csv('Master_Camera.csv')

In [318]:
Master_Camera.drop(["Unnamed: 0"], axis = 1, inplace = True)
Master_Camera.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min
0,1,687143.0,523.0,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,0.0,1,0,28.0,10.0
1,2,3449874.0,3058.0,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,0.0,1,0,29.0,12.5
2,3,3834486.0,3060.0,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,1.0,1,0,33.0,13.5
3,4,3359335.0,2902.0,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,0.550000,1.647615,0.294951,1.116377,0.121612,0.0,1,0,33.5,14.5
4,5,1443658.0,1226.0,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,0.550017,1.646634,0.294752,1.116378,0.121538,0.0,1,0,33.5,15.0

In [319]:
Master_Camera.columns

Index(['Week', 'gmv_sum', 'units_sum', 'sla_mean', 'product_mrp_mean',
       'product_mrp_sum', 'product_procurement_sla_mean',
       'Weekly_Investment_Total_mean', 'Weekly_Investment_TV_mean',
       'Weekly_Investment_Digital_mean', 'Weekly_Investment_Sponsorship_mean',
       'Weekly_Investment_Content_Marketing_mean',
       'Weekly_Investment_Online_Marketing_mean',
       'Weekly_Investment_affiliates_mean', 'Weekly_Investment_SEM_mean',
       'Weekly_Investment_Radio_mean', 'Weekly_Investment_Other_mean',
       'NPS_mean', 'Pay_Day_Flag', 's1_fact.order_payment_type_sum',
       'Prepaid_Flag_sum', 'Weekly_TV_adstock_mean',
       'Weekly_Digital_adstock_mean', 'Weekly_Sponsorship_adstock_mean',
       'Weekly_Online_Marketing_adstock_mean', 'Weekly_SEM_adstock_mean',
       'Weekly_affiliates_adstock_mean', 'Sale_Flag', 'Rain_Flag', 'Snow_Flag',
       'Max Temp (°C)_max', 'Min Temp (°C)_min'],
      dtype='object')

In [320]:
Master_Camera.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 32 columns):
Week                                        52 non-null int64
gmv_sum                                     52 non-null float64
units_sum                                   52 non-null float64
sla_mean                                    52 non-null float64
product_mrp_mean                            52 non-null float64
product_mrp_sum                             52 non-null float64
product_procurement_sla_mean                52 non-null float64
Weekly_Investment_Total_mean                52 non-null float64
Weekly_Investment_TV_mean                   52 non-null float64
Weekly_Investment_Digital_mean              52 non-null float64
Weekly_Investment_Sponsorship_mean          52 non-null float64
Weekly_Investment_Content_Marketing_mean    52 non-null float64
Weekly_Investment_Online_Marketing_mean     52 non-null float64
Weekly_Investment_affiliates_mean           52 non-null float64
Weekly_Investment_SEM_mean                  52 non-null float64
Weekly_Investment_Radio_mean                52 non-null float64
Weekly_Investment_Other_mean                52 non-null float64
NPS_mean                                    52 non-null float64
Pay_Day_Flag                                52 non-null float64
s1_fact.order_payment_type_sum              52 non-null float64
Prepaid_Flag_sum                            52 non-null float64
Weekly_TV_adstock_mean                      52 non-null float64
Weekly_Digital_adstock_mean                 52 non-null float64
Weekly_Sponsorship_adstock_mean             52 non-null float64
Weekly_Online_Marketing_adstock_mean        52 non-null float64
Weekly_SEM_adstock_mean                     52 non-null float64
Weekly_affiliates_adstock_mean              52 non-null float64
Sale_Flag                                   52 non-null float64
Rain_Flag                                   52 non-null int64
Snow_Flag                                   52 non-null int64
Max Temp (°C)_max                           52 non-null float64
Min Temp (°C)_min                           52 non-null float64
dtypes: float64(29), int64(3)
memory usage: 13.1 KB

In [321]:
Master_Camera.describe()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Digital_adstock_mean,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min
count,52.000000,5.200000e+01,52.000000,52.000000,52.000000,5.200000e+01,52.000000,52.000000,52.000000,52.000000,...,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,27.365385,2.311202e+06,4092.846154,6.045328,2018.722309,8.061515e+06,2.612363,15.875671,0.848953,0.555270,...,1.047465,12.949794,6.793828,3.232181,2.151606,0.269231,0.788462,0.153846,21.391346,3.682692
std,15.361052,2.252505e+06,2024.481530,0.453932,305.532283,3.986080e+06,0.348948,9.470041,0.551365,0.667700,...,0.729498,6.317353,3.075143,1.876069,0.973211,0.447888,0.412384,0.364321,9.164679,9.133556
min,1.000000,0.000000e+00,1.000000,4.714989,716.666667,1.990000e+03,1.000000,0.000000,0.000000,0.100000,...,0.490000,1.060104,0.176196,1.116377,0.077180,0.000000,0.000000,0.000000,-5.000000,-18.000000
25%,14.750000,1.124000e+03,3298.000000,5.798658,1864.626890,6.777334e+06,2.434132,10.680000,0.370000,0.260098,...,0.560000,11.278469,6.404659,2.152843,2.011734,0.000000,1.000000,0.000000,15.875000,-3.625000
50%,27.500000,3.012032e+06,3975.500000,6.032418,2030.498053,7.840427e+06,2.636678,15.793981,0.900000,0.320000,...,0.788420,13.082098,8.021926,2.604762,2.633359,0.000000,1.000000,0.000000,22.250000,4.750000
75%,40.250000,3.716690e+06,5200.750000,6.300406,2215.175270,9.507351e+06,2.780369,21.600000,1.198465,0.559649,...,1.204799,14.906681,9.030499,4.196380,2.857448,1.000000,1.000000,0.000000,29.000000,13.000000
max,53.000000,1.123168e+07,10218.000000,7.666667,2492.768932,2.278236e+07,4.000000,37.810000,2.070000,2.800000,...,3.110000,26.057550,9.586060,8.063207,3.028860,1.000000,1.000000,1.000000,35.000000,18.000000

In [322]:
#Creating Promoting Pricing Effect

#Calculating percentage of discount offered.
Master_Camera['discount_off_percent'] = ((Master_Camera['product_mrp_mean']-Master_Camera['gmv_sum'])/Master_Camera['product_mrp_mean'])*100

In [323]:
Master_Camera.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Sponsorship_adstock_mean,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent
0,1,687143.0,523.0,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,0.0,1,0,28.0,10.0,-27465.451060
1,2,3449874.0,3058.0,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,0.0,1,0,29.0,12.5,-156499.722428
2,3,3834486.0,3060.0,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,1.0,1,0,33.0,13.5,-165384.593916
3,4,3359335.0,2902.0,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,1.647615,0.294951,1.116377,0.121612,0.0,1,0,33.5,14.5,-156742.414192
4,5,1443658.0,1226.0,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,1.646634,0.294752,1.116378,0.121538,0.0,1,0,33.5,15.0,-67079.382927

In [324]:
#Calculating List Price for all skus
Master_Camera['list_price'] = (Master_Camera['gmv_sum']/Master_Camera['units_sum'])

In [325]:
Master_Camera.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_Online_Marketing_adstock_mean,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent,list_price
0,1,687143.0,523.0,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,0.0,1,0,28.0,10.0,-27465.451060,1313.848948
1,2,3449874.0,3058.0,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,0.0,1,0,29.0,12.5,-156499.722428,1128.147155
2,3,3834486.0,3060.0,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,1.0,1,0,33.0,13.5,-165384.593916,1253.100000
3,4,3359335.0,2902.0,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,0.294951,1.116377,0.121612,0.0,1,0,33.5,14.5,-156742.414192,1157.593039
4,5,1443658.0,1226.0,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,0.294752,1.116378,0.121538,0.0,1,0,33.5,15.0,-67079.382927,1177.535073

In [326]:
week_range = range(0,52,1)

In [327]:
#Calculating Shelf Price inflation
for i in week_range:
    Master_Camera.loc[(Master_Camera['Week'] == i+1), 'shelf_price_infl'] = Master_Camera.iloc[i,33]/ Master_Camera.iloc[i-1,33]

In [328]:
Master_Camera.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent,list_price,shelf_price_infl
0,1,687143.0,523.0,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,28.0,10.0,-27465.451060,1313.848948,62.309250
1,2,3449874.0,3058.0,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,29.0,12.5,-156499.722428,1128.147155,0.858658
2,3,3834486.0,3060.0,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,1.116377,0.121612,1.0,1,0,33.0,13.5,-165384.593916,1253.100000,1.110759
3,4,3359335.0,2902.0,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,33.5,14.5,-156742.414192,1157.593039,0.923783
4,5,1443658.0,1226.0,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,1.116378,0.121538,0.0,1,0,33.5,15.0,-67079.382927,1177.535073,1.017227

In [329]:
Master_Camera['shelf_price_infl'].fillna(0,inplace=True)
Master_Camera['shelf_price_infl'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
Name: shelf_price_infl, dtype: bool

In [330]:
Master_Camera.loc[(Master_Camera['shelf_price_infl'] == np.inf), 'shelf_price_infl'] = 0.0

In [331]:
Master_Camera['shelf_price_infl']

0     62.309250
1      0.858658
2      1.110759
3      0.923783
4      1.017227
5      0.396025
6      0.641172
7      0.905668
8      1.106084
9      0.983791
10     0.836751
11     0.992716
12     1.087397
13     1.036605
14     0.866963
15     1.143352
16     0.984449
17     0.890846
18     1.217744
19     0.900508
20     0.000000
21     0.000000
22     0.000000
23     0.000000
24     0.000000
25     1.258213
26     1.149719
27     1.306790
28     0.881118
29     0.781010
30     1.278259
31     0.887020
32     0.754581
33     1.504354
34     0.869282
35     0.885335
36     0.830586
37     0.286989
38     0.000000
39     0.000000
40     0.000000
41     0.000000
42     0.000000
43     0.000000
44     0.000000
45     0.000000
46     0.000000
47     1.486108
48     1.117175
49     1.090747
50     0.913094
51     0.000000
Name: shelf_price_infl, dtype: float64

In [332]:
Master_Camera.head()

,Week,gmv_sum,units_sum,sla_mean,product_mrp_mean,product_mrp_sum,product_procurement_sla_mean,Weekly_Investment_Total_mean,Weekly_Investment_TV_mean,Weekly_Investment_Digital_mean,...,Weekly_SEM_adstock_mean,Weekly_affiliates_adstock_mean,Sale_Flag,Rain_Flag,Snow_Flag,Max Temp (°C)_max,Min Temp (°C)_min,discount_off_percent,list_price,shelf_price_infl
0,1,687143.0,523.0,5.805825,2492.768932,1283776.0,2.699029,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,28.0,10.0,-27465.451060,1313.848948,62.309250
1,2,3449874.0,3058.0,6.793416,2202.988579,6558297.0,2.657709,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,29.0,12.5,-156499.722428,1128.147155,0.858658
2,3,3834486.0,3060.0,6.116667,2317.125667,6951377.0,2.734000,0.000000,0.050000,0.560000,...,1.116377,0.121612,1.0,1,0,33.0,13.5,-165384.593916,1253.100000,1.110759
3,4,3359335.0,2902.0,6.294076,2141.853667,6074297.0,2.722496,0.000000,0.050000,0.560000,...,1.116377,0.121612,0.0,1,0,33.5,14.5,-156742.414192,1157.593039,0.923783
4,5,1443658.0,1226.0,6.373434,2148.959900,2572305.0,2.739348,0.001888,0.049916,0.559532,...,1.116378,0.121538,0.0,1,0,33.5,15.0,-67079.382927,1177.535073,1.017227

In [333]:
#Implementing Distributed Lag Model with LinearRegression for CameraAccessory
y = Master_Camera.pop('gmv_sum')
X = Master_Camera

In [334]:
import statsmodels.api as sm

# Add a constant

X_lm = sm.add_constant(X)

# Create a first fitted model
lr = sm.OLS(y, X_lm).fit()

In [336]:
print(lr.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                gmv_sum   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.998
Method:                 Least Squares   F-statistic:                     938.0
Date:                Mon, 16 Sep 2019   Prob (F-statistic):           2.44e-29
Time:                        13:22:58   Log-Likelihood:                -650.84
No. Observations:                  52   AIC:                             1360.
Df Residuals:                      23   BIC:                             1416.
Df Model:                          28
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                    -4.457e+05   3.18e+05     -1.402      0.174    -1.1e+06    2.12e+05
Week                                     -4537.2959   1.73e+04     -0.262      0.796   -4.04e+04    3.13e+04
units_sum                                 3231.2011   1863.639      1.734      0.096    -624.030    7086.433
sla_mean                                 -2.039e+05   8.95e+04     -2.277      0.032   -3.89e+05   -1.87e+04
product_mrp_mean                          -484.5076    310.834     -1.559      0.133   -1127.516     158.501
product_mrp_sum                              0.2346      0.062      3.773      0.001       0.106       0.363
product_procurement_sla_mean             -1.734e+05   1.36e+05     -1.271      0.216   -4.55e+05    1.09e+05
Weekly_Investment_Total_mean              2.177e+05   9.85e+04      2.210      0.037    1.39e+04    4.22e+05
Weekly_Investment_TV_mean                -1.895e+06   4.66e+05     -4.066      0.000   -2.86e+06   -9.31e+05
Weekly_Investment_Digital_mean           -1.618e+06    8.6e+05     -1.880      0.073    -3.4e+06    1.62e+05
Weekly_Investment_Sponsorship_mean       -1.229e+05    1.5e+05     -0.819      0.421   -4.34e+05    1.88e+05
Weekly_Investment_Content_Marketing_mean  9.917e+05   1.43e+06      0.695      0.494   -1.96e+06    3.95e+06
Weekly_Investment_Online_Marketing_mean  -7.517e+05   4.78e+05     -1.572      0.130   -1.74e+06    2.38e+05
Weekly_Investment_affiliates_mean        -2.019e+05    1.2e+06     -0.169      0.868   -2.68e+06    2.27e+06
Weekly_Investment_SEM_mean                4.775e+05   1.93e+05      2.469      0.021    7.75e+04    8.77e+05
Weekly_Investment_Radio_mean              4.061e+05    7.5e+04      5.418      0.000    2.51e+05    5.61e+05
Weekly_Investment_Other_mean             -2.872e+05   1.08e+05     -2.664      0.014    -5.1e+05   -6.42e+04
NPS_mean                                  5.373e+04   1.85e+04      2.909      0.008    1.55e+04    9.19e+04
Pay_Day_Flag                              6.027e+04   3.47e+04      1.737      0.096   -1.15e+04    1.32e+05
s1_fact.order_payment_type_sum           -3703.1870   1852.129     -1.999      0.058   -7534.608     128.234
Prepaid_Flag_sum                         -3712.1695   1839.442     -2.018      0.055   -7517.346      93.007
Weekly_TV_adstock_mean                    1.592e+06   3.21e+05      4.964      0.000    9.28e+05    2.25e+06
Weekly_Digital_adstock_mean              -1.852e+06   1.48e+06     -1.250      0.224   -4.92e+06    1.21e+06
Weekly_Sponsorship_adstock_mean           9.072e+04   1.42e+05      0.641      0.528   -2.02e+05    3.83e+05
Weekly_Online_Marketing_adstock_mean     -2.207e+05   3.71e+05     -0.595      0.557   -9.88e+05    5.46e+05
Weekly_SEM_adstock_mean                   4.859e+05   9.74e+05      0.499      0.622   -1.53e+06     2.5e+06
Weekly_affiliates_adstock_mean            1.391e+05   8.78e+05      0.159      0.875   -1.68e+06    1.95e+06
Sale_Flag                                 -740.8651   4.49e+04     -0.016      0.987   -9.37e+04    9.22e+04
Rain_Flag                                -7.118e+04    5.3e+04     -1.343      0.192   -1.81e+05    3.85e+04
Snow_Flag                                 -8.93e+04   6.41e+04     -1.393      0.177   -2.22e+05    4.33e+04
Max Temp (°C)_max                        -1.835e+04   5541.850     -3.310      0.003   -2.98e+04   -6880.950
Min Temp (°C)_min                         3882.2104   5596.079      0.694      0.495   -7694.160    1.55e+04
discount_off_percent                       -21.1150      0.611    -34.533      0.000     -22.380     -19.850
list_price                                1717.9230    381.040      4.509      0.000     929.681    2506.165
shelf_price_infl                         -1409.6610   2545.702     -0.554      0.585   -6675.848    3856.525
==============================================================================
Omnibus:                        0.594   Durbin-Watson:                   2.112
Prob(Omnibus):                  0.743   Jarque-Bera (JB):                0.158
Skew:                           0.101   Prob(JB):                        0.924
Kurtosis:                       3.179   Cond. No.                     1.65e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.54e-17. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.